### PR TITLE
Update to 2.6.3

### PR DESCRIPTION
**Pull request by ukd1**
It doesn't appear to need updates to gems > 2.5

### CODE REVIEW

**Comment by kruszczynski** [comment]
Don't we just use `circlemator:latest` and that's auto-built from master?

**Comment by grodowski** [comment]
Yes, that's how it is supposed to work, however the DockerHub <> Github integration was broken and builds didn't trigger.

**Comment by ukd1** [comment]
> Yes, that's how it is supposed to work, however the DockerHub <> Github integration was broken and builds didn't trigger.

image

I'm looking in to why, but looks like we don't change config very much.

**Comment by grodowski** [comment]
When I last looked at this, the build config showed a `rainforest-dockerbot` user that was authorized, but without access to any repos. Now it says that GH is not linked at all

**Comment by ukd1** [comment]
This should pass when GCR is setup properly, waiting on rainforestapp/infrastructure#275

**Pull request closed without merging**
